/**
 * Templates used by the deploy bridge — commit message + PR title + PR body.
 *
 * Kept deliberately minimal for alpha. R-POLISH can wire real URLs and
 * richer markdown once the orchestrator has a stable base URL to link to.
 */

export interface IssueForTemplates {
  id: string;
  number: number;
  title: string;
}

export interface RunForTemplates {
  id: string;
}

export interface ProjectForTemplates {
  id: string;
  name: string;
}

export interface CommitMessageInput {
  issue: IssueForTemplates;
  run: RunForTemplates;
  project: ProjectForTemplates;
  stageName?: string | null;
}

export function buildCommitMessage(input: CommitMessageInput): string {
  const prefix = input.stageName ?? 'fluxaos';
  const header = `${prefix}: ${input.issue.title} (#${input.issue.number})`;
  const body = `fluxaOS pipeline run ${input.run.id}`;
  return `${header}\n\n${body}`;
}

export function buildPrTitle(issue: IssueForTemplates): string {
  return `${issue.title} (#${issue.number})`;
}

export interface PrBodyInput {
  issue: IssueForTemplates;
  run: RunForTemplates;
  project: ProjectForTemplates;
  commitSha?: string;
}

export function buildPrBody(input: PrBodyInput): string {
  const issueRef = `fluxaos://issues/${input.issue.id}`;
  const runRef = `fluxaos://runs/${input.run.id}`;
  const lines: string[] = [
    '## Issue',
    '',
    `[#${input.issue.number} — ${input.issue.title}](${issueRef})`,
    '',
    '## Pipeline Run',
    '',
    `Run: [${input.run.id}](${runRef})`,
  ];
  if (input.commitSha) {
    lines.push('', `Commit: \`${input.commitSha}\``);
  }
  lines.push('', '## Generated by fluxaOS');
  return lines.join('\n');
}
