# DO NOT EDIT this file directly. It is maintained by fhc sync and will be overwritten.
# Source: templates/tests-browser/conftest.py in fh-commons

"""
Browser Test Configuration - Playwright fixtures and configuration.

Synced from fh-commons templates. DO NOT EDIT directly.
Edit templates/tests-browser/conftest.py in fh-commons instead.

These tests use real Playwright browser instances to verify webapp behavior.
"""

import json
from pathlib import Path

import pytest

# Playwright imports - check if available
try:
    from playwright.sync_api import sync_playwright

    PLAYWRIGHT_AVAILABLE = True
except ImportError:
    PLAYWRIGHT_AVAILABLE = False
    sync_playwright = None  # type: ignore[assignment, misc]


# =============================================================================
# Screenshot directory (config-driven)
# =============================================================================


def _get_screenshot_dir() -> Path:
    """Get screenshot directory from shared config, with fallback."""
    project_root = Path(__file__).parent.parent.parent
    config_path = project_root / "config" / "shared.json"
    if config_path.exists():
        config = json.loads(config_path.read_text())
        rel_path = config.get("testing", {}).get("browser_tests", {}).get("screenshot_dir")
        if rel_path:
            return project_root / rel_path
    return Path(__file__).parent / "screenshots"


SCREENSHOT_DIR = _get_screenshot_dir()


# =============================================================================
# Skip decorator for playwright unavailable
# =============================================================================


def requires_playwright(func):
    """Decorator to skip test if playwright is not installed."""
    return pytest.mark.skipif(
        not PLAYWRIGHT_AVAILABLE,
        reason="Playwright not installed. Install with: pip install playwright && playwright install chromium",
    )(func)


# =============================================================================
# Fixtures
# =============================================================================


@pytest.fixture(scope="session")
def playwright_instance():
    """Create a Playwright instance for the test session."""
    if not PLAYWRIGHT_AVAILABLE:
        pytest.skip("Playwright not installed")

    with sync_playwright() as p:
        yield p


@pytest.fixture(scope="session")
def browser_instance(playwright_instance):
    """Launch a browser for the test session."""
    try:
        browser = playwright_instance.chromium.launch(headless=True)
    except Exception as exc:
        pytest.skip(
            f"Playwright browser binary not available: {exc}\n"
            "Install with: playwright install chromium"
        )
    yield browser
    browser.close()


@pytest.fixture
def browser_context(browser_instance):
    """Create a browser context for test isolation."""
    context = browser_instance.new_context(
        viewport={"width": 1280, "height": 720},
        ignore_https_errors=True,
    )
    yield context
    context.close()


@pytest.fixture
def browser_page(browser_context):
    """Create a new page for each test."""
    page = browser_context.new_page()
    page.set_default_timeout(10000)  # 10 second timeout
    yield page
    page.close()


# =============================================================================
# Screenshot on failure
# =============================================================================


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    """Capture screenshot on test failure."""
    outcome = yield
    report = outcome.get_result()

    if report.when == "call" and report.failed:
        # Try to get the page fixture
        page = item.funcargs.get("browser_page")
        if page and hasattr(page, "screenshot"):
            # Create screenshots directory if needed
            SCREENSHOT_DIR.mkdir(parents=True, exist_ok=True)

            # Generate screenshot filename
            test_name = item.name.replace("/", "_").replace("::", "_")
            screenshot_path = SCREENSHOT_DIR / f"FAILED_{test_name}.png"

            try:
                page.screenshot(path=str(screenshot_path))
                print(f"\nScreenshot saved: {screenshot_path}")
            except Exception as e:
                print(f"\nFailed to capture screenshot: {e}")
