#!/bin/bash
# Script to update .claude command files for fluxaos
# This updates command references to use the flu CLI
# Generated by fhc setup-project

CLAUDE_DIR="/mnt/dev/fluxaos/.claude"
CLI_NAME="flu"

if [ ! -d "$CLAUDE_DIR" ]; then
    echo "Error: .claude directory not found at $CLAUDE_DIR"
    exit 1
fi

echo "Updating .claude command files..."
echo "Replacing 'fhc' with '$CLI_NAME' in all .md files"
echo ""

# Count files to be processed
file_count=$(find "$CLAUDE_DIR" -name "*.md" -type f | wc -l)
echo "Found $file_count markdown files to process"
echo ""

updated_count=0

# Process each markdown file
for file in "$CLAUDE_DIR"/*.md "$CLAUDE_DIR"/commands/*.md; do
    if [ -f "$file" ]; then
        # Check if file contains 'fhc' pattern (word boundary aware)
        if grep -qE '\bfhc\b' "$file" 2>/dev/null; then
            # Replace 'fhc' with CLI name (word boundary aware)
            sed -i "s/\bfhc\b/$CLI_NAME/g" "$file"
            echo "Updated: $(basename "$file")"
            updated_count=$((updated_count + 1))
        fi
    fi
done

echo ""
if [ "$updated_count" -eq 0 ]; then
    echo "All files already use correct CLI name ($CLI_NAME)"
else
    echo "Updated $updated_count files to use CLI name ($CLI_NAME)"
fi
